apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin13-call
  labels:
    app: admin13-call
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin13-call
  template:
    metadata:
      labels:
        app: admin13-call
    spec:
      containers:
        - name: admin13-call
          image: 271153858532.dkr.ecr.ap-northeast-2.amazonaws.com/admin13-call:v3
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5